language: python
dist: xenial
sudo: false
python:
  - "$TRAVIS_PYTHON_VERSION"
before_install:
  - pip install codecov
install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  # Create the environment.
  - conda install pyyaml
  - conda env create python=$TRAVIS_PYTHON_VERSION
  - source activate phylib
  - conda install pyqt
  # Dev requirements
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install -e .
script:
  - make test
after_success:
  - codecov
